
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/jpatest?serverTimezone=GMT&nullCatalogMeansCurrent=true&useUnicode=true&characterEncoding=utf-8
    username: "root"
    password: "123456"
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
#      ddl-auto: create
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  main:
    banner-mode: off
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

## 上传文件总的最大值
#  spring.servlet.multipart.max-request-size=10MB
#  # 单个文件的最大值
#  spring.servlet.multipart.max-file-size=10MB

  flyway:
    # 是否启用flyway
    enabled: false
    # 编码格式，默认UTF-8
    encoding: UTF-8
    # 迁移sql脚本文件存放路径，默认db/migration
    locations: classpath:db
    # 迁移sql脚本文件名称的前缀，默认V
    sql-migration-prefix: V
    # 迁移sql脚本文件名称的分隔符，默认2个下划线__
    sql-migration-separator: __
    # 迁移sql脚本文件名称的后缀
    sql-migration-suffixes: .sql
    # 迁移时是否进行校验，默认true
    validate-on-migrate: true
    # 当迁移发现数据库非空且存在没有元数据的表时，自动执行基准迁移，新建schema_version表
    baseline-on-migrate: true
